### PR TITLE
ENH: Moving to appdirs for example storage

### PR DESCRIPTION
**Pull request by sjsrey**
Using [appdirs](https://github.com/ActiveState/appdirs) to handle local storage of examples.

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]
This looks like a nice change and I can't think of possible negative consequences right now.

**Comment by jGaboardi** [comment]
I'm curious about what the `ci/travis/3{6,7}-latest-conda-forge.yaml` files are doing in here? To my knowledge we dropped support for Python 3.6 and we migrated from Travis to GHA. Also, Python 3.7 is covered in `ci/37.yaml`. Maybe these are used for something else I am missing?

**Comment by sjsrey** [comment]
> I'm curious about what the `ci/travis/3{6,7}-latest-conda-forge.yaml` files are doing in here? To my knowledge we dropped support for Python 3.6 and we migrated from Travis to GHA. Also, Python 3.7 is covered in `ci/37.yaml`. Maybe these are used for something else I am missing?

They are gone now.

**Comment by jGaboardi** [comment]
> > I'm curious about what the `ci/travis/3{6,7}-latest-conda-forge.yaml` files are doing in here? To my knowledge we dropped support for Python 3.6 and we migrated from Travis to GHA. Also, Python 3.7 is covered in `ci/37.yaml`. Maybe these are used for something else I am missing?
> 
> They are gone now.

It looks like the `ci/travis/3{6,7}-latest-conda-forge.yaml` files were merged into `master` in the PR, though. They should have bee removed, correct?

**Pull request merged**
