### PR TITLE
support cliques as a resolver of coincident points in Graph

### PR DESCRIPTION
**Pull request by knaaptime**
i think we were just missing a couple parens

### CODE REVIEW

**Comment by martinfleis** [comment]
The issue, as far as I remember it, was that `_induce_cliques` was not working properly. That is why I added `NotImplementedError`. I'd be happy to allow it again but the PR needs to come with extensive tests to ensure it all works as it is supposed to :).

**Comment by ljwolf** [comment]
I think there was an [issue after a bad rebase.](https://github.com/pysal/libpysal/pull/554#issuecomment-1695680478)

I can get some attention on it this week to fix.

**Comment by ljwolf** [comment]
I'm pretty certain that the issue was induced when we [switched from focal-indexed adjacency to non-indexed adjacency.](https://github.com/knaaptime/libpysal/pull/40). @knaaptime, I've sent a PR to your clique branch with the change.

The dual merge in [lines 76-82](https://github.com/knaaptime/libpysal/blob/cliques/libpysal/graph/_utils.py#L76) was supposed to match up the deduped ids back onto the clique ids, and then explode the cliques into their own links. This only works when the `adjtable` is indexed on `focal`. 

With this fix, tests still fail, but I think [the test answers are incorrect](https://github.com/knaaptime/libpysal/blob/cliques/libpysal/graph/tests/test_triangulation.py#L351)? In the tests, 0 and 4 are coincident. If 0 and 4 are coincident, then every link and backlink containing 0 *should also* contain 4. So, for example, link `(5,0)` is missing, as is link `(2,4)`.

So, the correct answer, I think, is: 

```python
exp_heads = numpy.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
       5, 5])
exp_tails = numpy.array([1, 3, 4, 5, 0, 2, 3, 4, 5, 1, 3, 5, 0, 1, 2, 4, 0, 1, 3, 5, 0, 1,
       2, 4])
```

The expand cliques correctly recovers this.

**Comment by ljwolf** [comment]
OK, after some further testing, I think I've confirmed the answers need to change, but I had to make sure to re-set the working values (like, `coordinates, ids, geoms, heads, tails, weights`) after expanding the cliques. 

I will change the tests, but the correct edge table is in the comment above.

**Comment by ljwolf** [comment]
This now also addresses #573. The fix was as described, but also exposed a few other minor issues in the implementation that have been fixed. 

example_output

**Comment by ljwolf** [comment]
Triangulation is done. I'm now verifying the usage in `_knn()`/`_kernel()`, so still WIP.

**Comment by ljwolf** [comment]
`_knn`/`_kernel` is done. Currently, I'm getting local failures in the round-tripping from sparse? The adjacency tables are the same, but comparing the graphs by equality is not. I'm not sure how/where this would have been introduced by this PR, and it's currently failing on main?

**Comment by ljwolf** [comment]
This is ready for review.

**Comment by martinfleis** [comment]
> Currently, I'm getting local failures in the round-tripping from sparse? The adjacency tables are the same, but comparing the graphs by equality is not. I'm not sure how/where this would have been introduced by this PR, and it's currently failing on main?

Could it be some issue with your local env? It seems to be work as expected on CI.

We have some issue with coincident points in the env with the minimum supported versions of dependencies for some reason...

**Comment by ljwolf** [comment]
then it must be something in my local environment. I will check out the failures in py3.10. I think that's likely a numba issue.

**Comment by ljwolf** [comment]
Not a numba issue, but rather needed a bit more than [4091467](https://github.com/pysal/libpysal/pull/647/commits/4091467aaa8bbcf29d3164bed359b58a6a1b4489) to fully fix #573.

**Comment by ljwolf** [comment]
Tests are passing, ready for review!

**Review by ljwolf — APPROVED** [review]

**Comment by ljwolf** [comment]
@knaaptime I can't assign you as a reviewer, but you probably should be one of the reviewers anyway, having motivated me to revisit this 😄

**Review by knaaptime — COMMENTED** [review]
you rule. But i also cant approve, apparently, since it's technically "my" pr 

so, approved. :P

**Review by martinfleis — APPROVED** [review]
I can approve :)

**Pull request merged**
