### PR TITLE
Update unittests, etc

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* adds Python 3.9 to testing schema
* update and standardizes `unittests.yml` and `release_and_publish.yml`
  * uses `micromamba` action for much speedier env resolves

### CODE REVIEW

**Comment by jGaboardi** [comment]
@sjsrey we may want to take this opportunity to drop support for Python 3.6. Thought?

**Review by sjsrey — APPROVED** [review]

**Comment by sjsrey** [comment]
@jGaboardi should we do another post release to fix docs?

**Comment by jGaboardi** [comment]
Yes, now the [manual trigger is available](https://github.com/pysal/libpysal/actions/workflows/build_docs.yml) let's try to bump another `post` release and trigger a doc build. After that we should be able to change the [page source](https://github.com/pysal/libpysal/settings/pages) to the `gh-pages/root` branch.

**Comment by sjsrey** [comment]
I will do the bump and post.

**Pull request merged**
