### PR TITLE
BUG: fix weights plotting

### LINKED ISSUE #525: W.plot() raises TypeError due to indexing a GeoDataFrame with a dict
Exception raised when working through the spatial weights tutorial: https://pysal.org/libpysal/notebooks/weights.html

Reproducing the issue:
```
import libpysal
import matplotlib.pyplot as plt

from libpysal.weights import Queen, Rook, KNN
import geopandas
pth = libpysal.examples.get_path("mexicojoin.shp")
gdf = geopandas.read_file(pth)

w_rook = Rook.from_dataframe(gdf)
ax = gdf.plot(edgecolor='grey', facecolor='w')
f,ax = w_rook.plot(gdf, ax=ax,
        edge_kws=dict(color='r', linestyle=':', linewidth=1),
        node_kws=dict(marker=''))
```

Throws:
```
TypeError: Passing a dict as an indexer is not supported. Use a list instead.
```

- Platform information:
```
posix linux
posix.uname_result(sysname='Linux', nodename='XXX', release='5.19.0-41-generic', version='#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2', machine='x86_64')
```
- Python version: 
```
3.10.10 (main, Mar 14 2023, 16:03:24) [GCC 11.3.0]
```
- SciPy version:
```
1.10.1
```
- NumPy version:
```
1.24.3
```

- Geopandas version:
```
0.13.0
```

- Pandas version
```
2.0.1
```

- Libpysal version
```
4.7.0
```

### PR DESCRIPTION
**Pull request by martinfleis**
Closes #525

We currently do not have any test suite for plotting, so I am not adding any tests here. Will add some as part of the weights refactoring which will include plotting refactoring as well.

### CODE REVIEW

**Comment by jGaboardi** [comment]
[Failure](https://github.com/pysal/libpysal/actions/runs/5555515835/jobs/10146784121?pr=533#step:4:1646):

```
FAILED libpysal/weights/tests/test_weights.py::TestW::test_to_sparse - AttributeError: module 'scipy.sparse' has no attribute '_arrays'
```

**Comment by martinfleis** [comment]
@jGaboardi that is the one I fixed in parallel in #532

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
#### re: plotting tests
I've had success with `matplotlib`'s  decorator – [`image_comparison`](https://matplotlib.org/stable/devel/testing.html#writing-an-image-comparison-test)

We should probably open a specific issue for this.

**Comment by martinfleis** [comment]
I think we have some issue like this in splot?

**Comment by jGaboardi** [comment]
xref https://github.com/pysal/splot/issues/145

**Pull request merged**
