### PR TITLE
[WIP] ensure safe returns for small n alphashapes

### PR DESCRIPTION
**Pull request by ljwolf**
this addresses #111.

My testing stack is broken at the moment, so I'm relying on travis for unittests. 

Will tag a reviewer once/if they pass.

### CODE REVIEW

**Comment by ljwolf** [comment]
tests now pass. I've added the small-N alpha shaping to any data with less than 4 points, since qhull should take care of anything with four or more points.

**Comment by ljwolf** [comment]
bumping this... would like to get this into the next libpysal.

**Comment by ljwolf** [comment]
FYI on this, I still run into some kind of hairy behaviour here. The `buffer(0)` trick ensures that all return types are `POLYGON`. But, if you're `n == 2` or `n==1`, then this returns `POLYGON EMPTY`. This isn't the friendliest thing, especially since [`geopandas` doesn't like spatial joints with empty polygons](https://github.com/geopandas/geopandas/issues/944)...

**Comment by jGaboardi** [comment]
hmmmm

**Pull request merged**
