### PR TITLE
CI against Python 3.12

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* starts testing against Python 3.12
* drop Python 3.8 & 3.9 support
* cleans up dips / req in `pyproject.toml`, `ci/*`, and `environment.yml`
-----

Current situation:
* 3.10 & 3.11
  * all good
* 3.12
  * Not quite there – [`numba` can't be resolved yet](https://github.com/pysal/libpysal/actions/runs/6598600274/job/17926744210#step:3:34) but this seems like it will be [good to go soon](https://github.com/numba/numba/issues/9197#issuecomment-1766428178).

### CODE REVIEW

**Comment by jGaboardi** [comment]
* Python 3.12 passing with no options
* Other versions failing with known issues with latest `networkx` release (see here in [`graph._set_ops.isomorphic()`](https://github.com/pysal/libpysal/blob/b9b58e329481df20bec71fb3aed44c22fc88094c/libpysal/graph/_set_ops.py#L186))

**Comment by jGaboardi** [comment]
@martinfleis @sjsrey 

Should we:
1. drop 3.8 + 3.9 and have 3.10 as minimal; or
2. only drop 3.8 and keep 3.9 as minimal

**Comment by sjsrey** [comment]
> @martinfleis @sjsrey
> 
> Should we:
> 
>     1. drop 3.8 + 3.9 and have 3.10 as minimal; or
> 
>     2. only drop 3.8 and keep 3.9 as minimal

If we follow [nep](https://numpy.org/neps/nep-0029-deprecation_policy.html), 3.10 would be minimal with 3.12 out now.

**Review by sjsrey — APPROVED** [review]
lgtm

**Comment by jGaboardi** [comment]
[`numba` can't be resolved yet](https://github.com/pysal/libpysal/actions/runs/6598600274/job/17926744210#step:3:34) but this seems like it will be [good to go soon](https://github.com/numba/numba/issues/9197#issuecomment-1766428178).

**Comment by martinfleis** [comment]
Can we just comment-out `numba` from 3.12 envs for now and merge? We can revise once numba is available.

**Comment by jGaboardi** [comment]
> Can we just comment-out `numba` from 3.12 envs for now and merge? We can revise once numba is available.

This sounds reasonable. I will do that and push up.

Also, I am working on #588 right now. Shall I incorporate that into this PR or in another?

**Comment by martinfleis** [comment]
Let's do it as a follow-up. That one will likely see some code changes.

**Comment by jGaboardi** [comment]
* [`ci/312-dev`](https://github.com/pysal/libpysal/actions/runs/6599056504/job/17927663357?pr=585#step:5:1696) failing due to --> https://github.com/pysal/libpysal/pull/587
* Intersting [`libpysal` version](https://github.com/pysal/libpysal/actions/runs/6599056504/job/17927663543?pr=585#step:4:51) --> `Successfully installed libpysal-0.1.dev1+g344cccc`

**Comment by jGaboardi** [comment]
@martinfleis this is now ready for review.

**Comment by martinfleis** [comment]
> Intersting [libpysal version](https://github.com/pysal/libpysal/actions/runs/6599056504/job/17927663543?pr=585#step:4:51) --> Successfully installed libpysal-0.1.dev1+g344cccc

We need to ensure the tags are present. This may cause trouble. We need 

```yml
- uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags.
```

**Comment by jGaboardi** [comment]
Add to this PR, correct?

**Comment by martinfleis** [comment]
Yes please :)

**Comment by jGaboardi** [comment]
I guess now we need to check across the ecosystem for that...

**Comment by jGaboardi** [comment]
Seeing the proper `libpysal` version now.

* [before](https://github.com/pysal/libpysal/actions/runs/6599056504/job/17927663134#step:4:49): `libpysal-0.1.dev1+g344cccc`
* [now](https://github.com/pysal/libpysal/actions/runs/6599191393/job/17927957912?pr=585#step:4:49): `libpysal-4.8.1.dev19+gbb16a5eb`

**Comment by jGaboardi** [comment]
Once this is reviewed & merged I will tackle #588.

**Review by martinfleis — APPROVED** [review]
Looks great! Thanks!

I got a branch tackling most of the warnings in CI, so that should also be resolved shortly.

**Comment by martinfleis** [comment]
@jGaboardi Why did we include xarray as a hard dependency here? Is that because we actually hard depend on it? If so we should refactor. Something around that is causing conda-forge to fail.

**Comment by jGaboardi** [comment]
I suppose that was my oversight/mistake since there is a `from_xarray()` method in [`weights/contiguity.py`](https://github.com/pysal/libpysal/blob/6072541351c263c979cf0ca91ff70d019794048c/libpysal/weights/contiguity.py#L247) and `xarray` is imported [`weights/raster.py`](https://github.com/pysal/libpysal/blob/6072541351c263c979cf0ca91ff70d019794048c/libpysal/weights/raster.py#L391). However, these are clearly not hard deps.

I will put in a PR to fix this immediatly.

**Pull request merged**
