### PR TITLE
rebuild docs;

### PR DESCRIPTION
**Pull request by knaaptime**
this rebuilds the docs to fix the alignment problem

### CODE REVIEW

**Comment by sjsrey** [comment]
> this rebuilds the docs to fix the alignment problem

I updated the docs before I saw this - sorry.

Not sure what the specific changes were in this pr that I should incorporate?

**Comment by knaaptime** [comment]
there's no config change necessary, just need to make sure the sphinx and sphinx_bootstrap_theme in your environment are up to date

**Comment by sjsrey** [comment]
> there's no config change necessary, just need to make sure the sphinx and sphinx_bootstrap_theme in your environment are up to date

I rebuilt this morning with an updated env.

Does [this](https://pysal.org/libpysal/api.html) look like the fixes are made as intended in your original pr?  If so, we can close this.

**Comment by knaaptime** [comment]
yep, lets close

**Pull request closed without merging**
