### PR TITLE
pysal --> libpysal docs conv & modernizing .travis.yml

### PR DESCRIPTION
**Pull request by jGaboardi**
The justification for this PR is: 
- somehow we missed a ton of `import pysal` statements in the `io/` files ***and*** doctests were not being run for them until Tuesday this week (03/12/2019). no idea how this happened.
- removing quotes from python versions
- mandating the current version of Miniconda3 be uses, not Miniconda (archaic).

### CODE REVIEW

**Comment by jGaboardi** [comment]
pysal/pysal#1085

**Comment by jGaboardi** [comment]
Addressing #143

**Comment by jGaboardi** [comment]
#143 seems to be causing more issue, seemingly due to the difference between `conda` and `pip` version of `libpysal`. Rolling back strict enforcement.

**Comment by ljwolf** [comment]
why do our doctests just now fail? this is odd.

**Comment by jGaboardi** [comment]
@ljwolf some lagging/weirdness seems to be going on with both GitHub and Travis this morning (at least for me).

**Comment by jGaboardi** [comment]
@ljwolf At this point I have no idea why the doc tests are failing. My branch [is passing for the PR](https://travis-ci.com/jGaboardi/libpysal/builds/104089029).

**Comment by jGaboardi** [comment]
Addressing #144

**Comment by jGaboardi** [comment]
@sjsrey @ljwolf I have gotten the 25 `doctest` failures whittled down to 2. I will will create `Issues` for these failures and cross reference back to here.

**Comment by jGaboardi** [comment]
#145

**Comment by jGaboardi** [comment]
#146?

**Comment by jGaboardi** [comment]
@ljwolf @sjsrey This is ready for review.

overview:
- all `doctest`s now fixed
- `.travis.yml` modernized
- removal of `python2` functionality in [`59881bb`](https://github.com/pysal/libpysal/pull/142/commits/59881bbfd5e1d0b8c621171513bed362f87eb6b6#diff-ee3b2c15bc6ebd918f35ef01f69a7cba) and [`735cfa2`](https://github.com/pysal/libpysal/pull/142/commits/735cfa2c3d3f2d3226b29eec065e98c62eb28a2d)
- general cosmetic clean ups for `doctest`s and spacing 
- #143, #144, #145, #146 addressed

**Comment by sjsrey** [comment]
Great work digging into these

**Pull request merged**
