### PR TITLE
standardizing libpysal/io docs & ibpysal/cg docs

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR focuses on standardizing the `libpysal/io/*` and `libpysal/cg/*` docs. See #290, #291, #319, pysal/pysal#1174.

@sjsrey This is ready for review. It is 95% docstring standardization and 5% logic/code streaming. I have also added several functions to the api docs that had been left out earlier. The CI failure is due to a small decrease in the code coverage, not actual testing errors.

Shall I rebuild the actual doc html files or leave that until #290 is fully complete (or even next release)?

### CODE REVIEW

**Comment by jGaboardi** [comment]
pysal/libpysal#126

**Comment by jGaboardi** [comment]
@sjsrey This PR is ready for review.

**Comment by jGaboardi** [comment]
@sjsrey All tests green again.

**Review by sjsrey — APPROVED** [review]
Awesome work!

**Pull request merged**
