### PR TITLE
remove redundant `.coveragerc`

### LINKED ISSUE #602: remove `.coveragerc`
`.coveragerc` is now redundant as instructions are found in in [`pyproject.toml`](https://github.com/pysal/libpysal/blob/b6a03f240ef95d31a15cb45b9fb57e35595d7971/pyproject.toml#L109).

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR resolves #602.

### CODE REVIEW

**Comment by martinfleis** [comment]
The contents we have in `pyproject` does not match `coveragerc` for a reason?

**Comment by jGaboardi** [comment]
> I wonder if there is any reason not to be using `pytest-xdist` in `libpysal`?

Perhaps [this](https://github.com/pysal/libpysal/actions/runs/6627178517/job/18001574168?pr=604#step:5:390) has something to do with it?

```
ERROR libpysal/graph/tests/test_kernel.py - fiona.errors.DriverError: .shp file is unreadable, or corrupt.
ERROR libpysal/graph/tests/test_triangulation.py - fiona.errors.DriverError: .shp file is unreadable, or corrupt.
ERROR gw0
```

**Comment by jGaboardi** [comment]
Pretty significant runtime decrease in some, negligible in others. Any thoughts on the `fiona.errors.DriverError`, @martinfleis ?

**Comment by martinfleis** [comment]
> I wonder if there is any reason not to be using pytest-xdist in libpysal?

I have removed it recently precisely for the file access conflicts. We can try to resolve those by designing the test differently but let's deal with it separately if you feel this will significantly help.

**Comment by martinfleis** [comment]
> Is there anything else you'd like to see in pyproject.toml that I missing?

not really, I was just wondering why the difference.

**Review by martinfleis — APPROVED** [review]

**Pull request merged**
