### PR TITLE
finalise kernel constructors in graph 

### PR DESCRIPTION
**Pull request by martinfleis**
- `taper` is back and working properly.
- kernel constructors are tested
- fixed issues with conincident points
- exposes sklearn metrics outside knn

One question:

What shall be the behaviour of kernel when `k` is set but the bandwidth s too small so weight is zero, eliminating the link with taper? now the affected focal has less neighbors than K without a warning. I'd say we may warn but that is about it. You can retrieve the rest using `taper=False`.

_edited_

### CODE REVIEW

**Comment by jGaboardi** [comment]
Any idea what's going on with the [failures](https://github.com/pysal/libpysal/actions/runs/6266706510/job/17018225522?pr=571)?

**Comment by martinfleis** [comment]
Yes, will fix

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
Whoops, approved too soon.

**Comment by martinfleis** [comment]
@jGaboardi should be fixed now. I was too lazy to create an env without sklearn and it shows...

**Comment by martinfleis** [comment]
Gonna merge and continue with triangulation. Feel free to still review this, we can fix stuff in follow-ups.

**Pull request merged**
