### PR TITLE
bump supported Python versions and correct lat2SW doctest

### PR DESCRIPTION
**Pull request by jGaboardi**
Bumping  supporting Python versions in TravisCI to match pysal/pysal#1095

{3.5, 3.6} --> {3.6, 3.7}

### CODE REVIEW

**Comment by jGaboardi** [comment]
Failure does not appear to be do to the {3.6,3.7} upgrade, but a simple [failed doctest](https://travis-ci.org/pysal/libpysal/jobs/536544965#L1849-L1874). This seems to be an issue with `numpy` and is most likely related to current `pysal/pysal` build failures (dealing with`numpy`). The [failures in `pysal/pysal`](https://travis-ci.org/pysal/pysal/builds/536518887) appear to be related to numpy/numpy#10565.

```
======================================================================
FAIL: Doctest: libpysal.weights.util.lat2SW
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jGaboardi/libpysal/miniconda/envs/test-env/lib/python3.6/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for libpysal.weights.util.lat2SW
  File "/home/travis/build/jGaboardi/libpysal/libpysal/weights/util.py", line 1122, in lat2SW
----------------------------------------------------------------------
File "/home/travis/build/jGaboardi/libpysal/libpysal/weights/util.py", line 1156, in libpysal.weights.util.lat2SW
Failed example:
    w9[0,1]
Expected:
    1
Got:
    array(1, dtype=int8)
----------------------------------------------------------------------
File "/home/travis/build/jGaboardi/libpysal/libpysal/weights/util.py", line 1158, in libpysal.weights.util.lat2SW
Failed example:
    w9[3,6]
Expected:
    1
Got:
    array(1, dtype=int8)
```

**Comment by weikang9009** [comment]
Hi @jGaboardi, this seems to be related to [NumPy array scalar](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html#array-scalars)? After pulling your commits to my local machine and ran doctests locally, I ran into this error:
image
I am on Mac, python 3.7.3, numpy 1.16.3

**Comment by jGaboardi** [comment]
The tests for pass locally for me, both for Python `3.6` and `3.7.3`` with numpy 1.16.3`.

**Comment by sjsrey** [comment]
> The tests for pass locally for me, both for Python `3.6` and `3.7.3` with `numpy 1.16.3`.

I'm hitting the same failure that @weikang9009 reports (I'm on linux and python 3.7.1):

```
File "/home/serge/Dropbox/p/pysal/src/subpackages/libpysal/libpysal/weights/util.py", line 1156, in libpysal.weights.util.lat2SW
Failed example:
    w9[0,1]
Expected:
    array(1, dtype=int8)
Got:
    1
```

**Comment by sjsrey** [comment]
> ```
> ----------------------------------------------------------------------
> File "/home/serge/Dropbox/p/pysal/src/subpackages/libpysal/libpysal/weights/util.py", line 1156, in libpysal.weights.util.lat2SW
> Failed example:
>     w9[0,1]
> Expected:
>     array(1, dtype=int8)
> Got:
>     1
> ```

The local failures could be due to not replicating the travis envs for the version bump.

**Comment by jGaboardi** [comment]
So this is a bit strange, correct? The tests pass on locally (for me) and on Travis for 3.6 and 3.7, but fail for you guys.

**Comment by sjsrey** [comment]
The PR was passing on travis, so I merged.

**Pull request merged**
