### PR TITLE
New changelog conventions

### PR DESCRIPTION
**Pull request by sjsrey**
This is modeled after [how to keep a changelog ](https://keepachangelog.com/en/1.0.0/).

Opening up for discussion of conventions for how to keep our changelogs across the federation, using libpysal as a test case.

### CODE REVIEW

**Comment by sjsrey** [comment]
To avoid conflicts in the changelog, we might add a `digest` directory in the repo. In there we add a digest entry for each PR that we want to highlight in the changelog.

```
---
category: added
description: "No longer polling remotes on init"
d_url: https://github.com/pysal/libpysal/pull/504
contributor: sjsrey
c_url: https://github.com/sjsrey
status:
```

We add tooling that globs the digest directory for all entries that have empty `status`.
Each such entry is parsed and added to the `[Unrleased]` section and `category` of the `changelog.md` file.
For this entry the result would be something like:
```
# Changelog

## [Unreleased]
https://github.com/pysal/libpysal/compare/v4.7.0...master

### Added

- W.from_WSP
- W.to_sparse

### Changed
- [No longer polling remotes on init](https://github.com/pysal/libpysal/pull/504) [@sjsrey](https://github.com/sjsrey/)

```

After the changelog is updated, the digest entry gets updated: `status: logged`.
```
---
category: added
description: "No longer polling remotes on init"
d_url: https://github.com/pysal/libpysal/pull/504
contributor: sjsrey
c_url: https://github.com/sjsrey
status: logged
```


## Release
When it comes time to do the release, the changelog.md file goes from:

```
# Changelog

## [Unreleased]
https://github.com/pysal/libpysal/compare/v4.7.0...master

### Added

- W.from_WSP
- W.to_sparse

### Changed
- [No longer polling remotes on init](https://github.com/pysal/libpysal/pull/504) [@sjsrey](https://github.com/sjsrey/)

```

to

```
# Changelog

## [Unreleased]
https://github.com/pysal/libpysal/compare/v4.8.0...master



## [4.8.0](2023-01-12)

### Added

- W.from_WSP
- W.to_sparse

### Changed
- [No longer polling remotes on init](https://github.com/pysal/libpysal/pull/504) [@sjsrey](https://github.com/sjsrey/)

```

And we continue on post-release with the `[Unreleased]` version sections getting automatically populated with PRs and their digest entries.

This is a blend of curation (digests) and automation.

**Comment by sjsrey** [comment]
At the [Jan-23 dev meeting](https://hackmd.io/_ufiyW6BQfaso2U1TcsuFw?both), we decided to drop the digest idea and instead keep the `## [Unlreased]` heading. The latter will contain entries that come with Pull Requests that we want to publicize in a future release.

The PR template likely needs adjusting to reflect this.

**Comment by sjsrey** [comment]
It would be great to standardize the changelogs across all pysal packages.

Building on the work @jGaboardi has done with https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes, I think we can come up with a mapping of labels -> categories to get automated changelogs and release notes that are the same structure across the packages.

I re-added the WIP label so we can have a discussion of this to flesh the design out here.

**Comment by sjsrey** [comment]
We can add labels to already merged PRs, so this could be done now with an eye towards the meta release and aggregating across the packages.

**Comment by jGaboardi** [comment]
Always willing to try something new for a better user experience.

**Review by jGaboardi — APPROVED** [review]

**Review by martinfleis — APPROVED** [review]

**Review by knaaptime — APPROVED** [review]

**Comment by sjsrey** [comment]
Perhaps the new effort out of the scientific-python [changelist](https://github.com/scientific-python/changelist) is what we should use instead of rolling our own?

**Comment by knaaptime** [comment]
closing as we've had [this implemented](https://github.com/pysal/libpysal/blob/main/.github/release.yml) in the system for awhile and forgot to close the loop

**Pull request closed without merging**
