### PR TITLE
Update release action, etc. to prep for v4.8.0

### PR DESCRIPTION
**Pull request by jGaboardi**
xref: https://github.com/pysal/libpysal/issues/562#issuecomment-1742159791

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]

**Comment by jGaboardi** [comment]
Let's go ahead and merge so I can test action update?

**Comment by martinfleis** [comment]
Are you doing rc2?

**Comment by jGaboardi** [comment]
No, I just did `v4.8.0` Should I have done `v4.8.0rc2`?

**Comment by jGaboardi** [comment]
If so, can delete `v4.8.0` and redo.

**Comment by jGaboardi** [comment]
Failed anyway...

**Pull request merged**
