### PR TITLE
Do not poll remotes on init.

### PR DESCRIPTION
**Pull request by sjsrey**
Addresses #409

### CODE REVIEW

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
[Failure](https://github.com/pysal/libpysal/pull/410/checks?check_run_id=2814359252#step:10:526) seems to be due to an indexing issue upstream?

**Comment by sjsrey** [comment]
> [Failure](https://github.com/pysal/libpysal/pull/410/checks?check_run_id=2814359252#step:10:526) seems to be due to an indexing issue upstream?

Yes, I'm trying to fix these locally so that we can get to green.

**Comment by sjsrey** [comment]
> > [Failure](https://github.com/pysal/libpysal/pull/410/checks?check_run_id=2814359252#step:10:526) seems to be due to an indexing issue upstream?
> 
> Yes, I'm trying to fix these locally so that we can get to green.

Working locally, I have `test_dissolve` passing, but it is failing on the [ci](https://github.com/pysal/libpysal/pull/410/checks?check_run_id=2814436618#step:10:521)

**Comment by jGaboardi** [comment]
> > > [Failure](https://github.com/pysal/libpysal/pull/410/checks?check_run_id=2814359252#step:10:526) seems to be due to an indexing issue upstream?
> > 
> > 
> > Yes, I'm trying to fix these locally so that we can get to green.
> 
> Working locally, I have `test_dissolve` passing, but it is failing on the [ci](https://github.com/pysal/libpysal/pull/410/checks?check_run_id=2814436618#step:10:521)

hmmm I wonder what the deal is.

**Comment by sjsrey** [comment]
> > > > [Failure](https://github.com/pysal/libpysal/pull/410/checks?check_run_id=2814359252#step:10:526) seems to be due to an indexing issue upstream?
> > > 
> > > 
> > > Yes, I'm trying to fix these locally so that we can get to green.
> > 
> > 
> > Working locally, I have `test_dissolve` passing, but it is failing on the [ci](https://github.com/pysal/libpysal/pull/410/checks?check_run_id=2814436618#step:10:521)
> 
> hmmm I wonder what the deal is.

could be 3.6 versus 3.8 (local). will spin up a 3.6 locally and see.

**Comment by jGaboardi** [comment]
In the bigger picture, it may also be time for dropping 3.6 support for `libpysal` soon.

**Review by jGaboardi — APPROVED** [review]

**Pull request merged**
