### PR TITLE
Formatting via `ruff`

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* follows the example in [`xarray-contrib/xvec`](https://github.com/xarray-contrib/xvec/pull/54/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R7) for swapping out `black` for `ruff format` in formatting
* updates `pyproject.toml` of this
* makes several minor linting and formatting corrections
* updates contributing guidelines and `docs/install` for supported Python versions 

xref #589

### CODE REVIEW

**Comment by martinfleis** [comment]
Do we want to switch to ruff-format? I think it deserves some discussion. 

I am all for it. When doing that in `xvec` I was just curious but the ruff extension in VS Code is so good that I actually noticed a difference compared to black. And it is one less tool to deal with.

**Comment by jGaboardi** [comment]
> Do we want to switch to ruff-format? I think it deserves some discussion.
> 
> I am all for it. When doing that in `xvec` I was just curious but the ruff extension in VS Code is so good that I actually noticed a difference compared to black. And it is one less tool to deal with.

I am also all for it after realizing how simple the switch was, but also agree that we might want a broader discussion and approval. Shall we open an actual issue for this (and keep this PR open), or have more of a discussion in here?

**Comment by martinfleis** [comment]
I think it is fine to have it here.

**Review by martinfleis — APPROVED** [review]
Giving a formal approval to show my support.

**Comment by knaaptime** [comment]
interesting, hadnt seen xvec. We started doing something like that when geosnap started, but it became clear quickly that a long-form geodataframe was far better in our case (since vectors often have different geoms in different time slices...) anyway, another tangent :)

fine with the switch. I use the ruff extension in vscode locally

**Review by gegen07 — APPROVED** [review]
Looks good to me! Simplifying the environment is always a good enhancement.

**Comment by jGaboardi** [comment]
> fine with the switch. I use the ruff extension in vscode locally

@knaaptime Can you hit approve to make it more "formal?" 🤵‍♂️

**Review by knaaptime — APPROVED** [review]

**Comment by jGaboardi** [comment]
Nows this PR has 3 approvals. @gegen07 @knaaptime @martinfleis Shall we wait another week or so to see if anyone else has opinions? I am perfectly fine taking even longer to make sure we aren't being too hasty.

**Comment by martinfleis** [comment]
There's no rush. I'd wait for the next dev call next week.

**Comment by jGaboardi** [comment]
The dev team in attendance at the 2023-12-7 meeting [voted in favor of this implementation](https://github.com/orgs/pysal/discussions/1278#discussioncomment-7791889). Shall we go ahead and merge now or would it be better to wait longer?

**Pull request merged**
