### PR TITLE
use toarray in `W.full()`

### PR DESCRIPTION
**Pull request by knaaptime**
this uses the `toarray` method on a W's sparse matrix format to generate the dense matrix which is much faster than our manual approach

### CODE REVIEW

**Comment by knaaptime** [comment]
looks like the test failures stem from changed datasets and are already known. Everything passes fine locally

**Comment by ljwolf** [comment]
Looks good to me! I want to look into the failures, but relying on the sparse stuff is **the** way to go!

**Comment by knaaptime** [comment]
sweet. this has a big performance impact on several indices in `segregation` so thought it would be a good idea to upstream

**Comment by jGaboardi** [comment]
Test seem to be failing due to the [`SCIPY_7`](https://github.com/pysal/libpysal/blob/7df6d1808a089d22bf164fc7e3fbf83f571f8314/libpysal/weights/tests/test_util.py#L22) simply checking whether the installed `scipy` version is `1.7.0`, where to [`1.7.1`](https://github.com/scipy/scipy/releases) was released several weeks ago. Our unittests started failing [18 days ago](https://github.com/pysal/libpysal/runs/3266309665?check_suite_focus=true#step:3:854) once `1.7.1` was available on `conda-forge` (see [here](https://github.com/pysal/libpysal/runs/3256942087?check_suite_focus=true#step:3:854) for the last pass).

**Comment by jGaboardi** [comment]
This skip was added [here](https://github.com/pysal/libpysal/pull/418#issuecomment-869231564).

**Comment by jGaboardi** [comment]
I think I've narrowed down the change from scipy 1.6.3 to 1.7.0 relevant to `dia_matrix`. See the addition [here](https://github.com/scipy/scipy/compare/v1.6.3...v1.7.0#diff-8a57744fb65927efbe268b2d787bdb06d5b6d4c59a9aa67a924c002604a70460R240).

**Comment by ljwolf** [comment]
OK, if #426 passes, then this should get merged.

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
Conditional approval depending on #426

**Comment by ljwolf** [comment]
I've merged the current changes in #426 to this, so let's see if the things pass

**Comment by ljwolf** [comment]
Things pass :)

**Pull request merged**
