### PR TITLE
ENH: Neighbor detection for nonplanar enforced polygon collections.

### PR DESCRIPTION
**Pull request by sjsrey**
This addresses https://github.com/pysal/pysal/issues/889#issuecomment-396693495.

### CODE REVIEW

**Comment by ljwolf** [comment]
This includes/incorporates #50?

**Comment by sjsrey** [comment]
Yup on #50. Needed to merge to make all the tests pass on this.

**Comment by ljwolf** [comment]
To be sure, that skipif stuff would have this at the top:
```python
try:
    import geopandas as gpd
    HAS_GEOPANDAS = True
except ImportError:
    HAS_GEOPANDAS = False
```

and then, when it comes to the test method:
```python
@unittest.skipIf(not HAS_GEOPANDAS, "Missing geopandas, cannot test nonplanar neighbors")
def test_nonplanar_neighbors(self):
    ...
```

**Comment by ljwolf** [comment]
Great, my two points are addressed; :shipit:

**Comment by renanxcortes** [comment]
Hello, guys. Is this feature already in production? Is there a way to access the 'nonplanar_neighbors' attribute?

**Comment by renanxcortes** [comment]
Hello, guys. Is this feature in production? Is there a way to access the 'nonplanar_neighbors' attribute?

**Comment by ljwolf** [comment]
If you install this from github, you can use it immediately:
```
pip install git+git://github.com/pysal/libpysal.git
```
otherwise, you'll have to wait til we can make a release of libpysal.

**Comment by MohammadYoussef** [comment]
@ljwolf 
`pip install git+git://github.com/pysal/libpysal.git`
This still doesn't make the `nonpolar_neighbours` attribute work, is there another way?

**Pull request merged**
