### PR TITLE
update conf.py

### LINKED ISSUE #417: notebooks links in tutorials broken
It appears the some behavior in `Jinja`/`nbsphinx` has changed and now the links that are included at the top of tutorials don't work to send back to the original notebook ("This page was generated from `notebooks/xxxx.ipynb`"). This is affecting all submodules that rebuilt docs recently (libpysal, spaghetti, spopt, esda). To see that is was previously successful, see [spreg](https://pysal.org/spreg/notebooks/GM_Lag_example.html), which docs haven't been rebuild recently. The problem seems to be in the [`set docname`](https://github.com/pysal/libpysal/blob/ed19d4f3151201cd1cf8fcfa423c2b7837fea56f/docs/conf.py#L294) statement within `nbsphinx_prolog`, but I haven't been able to figure out how to correct the bad link generation. 

An example:
* previously generated:
  * https://github.com/pysal/spopt/blob/main/notebooks/reg-k-means.ipynb
* currently generated:
  * https://github.com/pysal/spopt//home/runner/work/spopt/spopt/docs/notebooks/reg-k-means.ipynb

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR resolves #417. We will need to regenerate the docs after merge.

### CODE REVIEW

**Review by sjsrey — APPROVED** [review]

**Comment by jGaboardi** [comment]
Strange that this would [error out](https://github.com/pysal/libpysal/pull/418/checks?check_run_id=2926981506#step:4:586).

```
def test_lat2SW(self):
     w9 = util.lat2SW(3, 3)
     rows, cols = w9.shape
     n = rows * cols
     pct_nonzero = w9.nnz / float(n)
>       self.assertEqual(pct_nonzero, 0.29629629629629628)
E       AssertionError: 0.345679012345679 != 0.2962962962962963
```

**Comment by jGaboardi** [comment]
@sjsrey shall we merge this or wait to figure out what's happening (presumably) upstream?

**Comment by sjsrey** [comment]
> Strange that this would [error out](https://github.com/pysal/libpysal/pull/418/checks?check_run_id=2926981506#step:4:586).
> 
> ```
> def test_lat2SW(self):
>      w9 = util.lat2SW(3, 3)
>      rows, cols = w9.shape
>      n = rows * cols
>      pct_nonzero = w9.nnz / float(n)
> >       self.assertEqual(pct_nonzero, 0.29629629629629628)
> E       AssertionError: 0.345679012345679 != 0.2962962962962963
> ```

Yes, it is strange. Running locally, the existing test passes.
I'm going to add more verbosity to the test to see what might be going wrong on the ci.

**Comment by sjsrey** [comment]
Looks like the ci is using scipy 1.7.0:
```
2021-06-27T22:34:36.8890906Z   scipy                          1.7.0         py38h7b17777_0     
```
locally when I'm using 1.6.3 it passes.

So I think you are correct in that the breakage is due to something upstream.

**Comment by sjsrey** [comment]
> Looks like the ci is using scipy 1.7.0:
> 
> ```
> 2021-06-27T22:34:36.8890906Z   scipy                          1.7.0         py38h7b17777_0     
> ```
> 
> locally when I'm using 1.6.3 it passes.
> 
> So I think you are correct in that the breakage is due to something upstream.

When testing scipy 1.7.0 locally, I get the same failure. `w9.nnz` is now 28, whereas before it was 24.

**Comment by sjsrey** [comment]
There seem to be some changes in scipy for  [dia](https://github.com/scipy/scipy/commit/23aa0cbaff1754f02acf074006399ba2edede2ef#diff-8a57744fb65927efbe268b2d787bdb06d5b6d4c59a9aa67a924c002604a70460) that might be related.

**Comment by jGaboardi** [comment]
> There seem to be some changes in scipy for [dia](https://github.com/scipy/scipy/commit/23aa0cbaff1754f02acf074006399ba2edede2ef#diff-8a57744fb65927efbe268b2d787bdb06d5b6d4c59a9aa67a924c002604a70460) that might be related.

A bit weird this would cause an error this evening when it was passing this morning. Seems like the most recent version of `scipy` was released [7 days ago](https://github.com/scipy/scipy/releases/tag/v1.7.0).

**Comment by sjsrey** [comment]
> > There seem to be some changes in scipy for [dia](https://github.com/scipy/scipy/commit/23aa0cbaff1754f02acf074006399ba2edede2ef#diff-8a57744fb65927efbe268b2d787bdb06d5b6d4c59a9aa67a924c002604a70460) that might be related.
> 
> A bit weird this would cause an error this evening when it was passing this morning. Seems like the most recent version of `scipy` was released [7 days ago](https://github.com/scipy/scipy/releases/tag/v1.7.0).

Yah, but I think 1.7.0 didn't make it into the ci workflow till sometime today as this morning we still at 1.6.3:
```
2021-06-27T18:43:29.6322933Z   scipy                                 1.6.3  py38h7b17777_0       conda-forge/linux-64      21 MB
```

Working on a skip for now in https://github.com/pysal/libpysal/pull/416

**Pull request merged**
