### PR TITLE
Update reqs for tests

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR makes adjusting following the adoption of `pytest`:
 * updates `requirements_tests.py` 
 * updates and blackens `setup.py` 

See [good integration practices](http://doc.pytest.org/en/3.0.2/goodpractices.html).

Also adding Python 3.8 to supported versions.

### CODE REVIEW

**Comment by jGaboardi** [comment]
+1.

In that case, should a 3.8 conda yaml be added to `/ci/travis` and called in `.travis.yml`?

**Comment by sjsrey** [comment]
> +1.
> 
> In that case, should a 3.8 conda yaml be added to `/ci/travis` and called in `.travis.yml`?

Incoming in #251

**Comment by jGaboardi** [comment]
We actually need to make another change to `.travis.yml`. Let me sneak that into this PR.

**Comment by sjsrey** [comment]
Let's wait till #251 gets finished before this one gets merged.

**Comment by knaaptime** [comment]
# [Codecov](https://codecov.io/gh/pysal/libpysal/pull/250?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@342ca3d`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/pysal/libpysal/pull/250?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##             master     #250   +/-   ##
=========================================
  Coverage          ?   80.76%           
=========================================
  Files             ?      116           
  Lines             ?    11459           
  Branches          ?        0           
=========================================
  Hits              ?     9255           
  Misses            ?     2204           
  Partials          ?        0           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/pysal/libpysal/pull/250?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/pysal/libpysal/pull/250?src=pr&el=footer). Last update [342ca3d...90f5c69](https://codecov.io/gh/pysal/libpysal/pull/250?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by jGaboardi** [comment]
@knaaptime Will this clear up once it is merged or is there something else we should do for this PR?

**Pull request merged**
