### PR TITLE
ENH: add Graph.apply, Graph.aggregate and allow callable as transformation in transform

### LINKED ISSUE #675: Interest in Graph.apply?
Within `momepy`, I often need to apply a custom function over an array of values or geometries of neighbours to any focal. I think that a function like `apply` shown below would go a long way in there. Shall we add it to Graph in this form? Or using different name?

```py
def apply(graph, y, func, **kwargs):
    grouper = y.take(
        graph.adjacency.index.codes[1]
        ).groupby(graph.adjacency.index.codes[0])
    result = grouper.agg(func, **kwargs)
    result.index = graph.unique_ids
    return result
```

This allows customised lags like getting median or mode or if ´y´is a GeoSeries apply a geo `func`.

```py
# median
apply(queen, df.area, np.median)

# IQR
apply(queen, df.area, scipy.stats.iqr)

# area of convex hull around neighbors
apply(queen, df.geometry, lambda x: x.unary_union.area)
```

_I love how simple this is on top of Graph_

### PR DESCRIPTION
**Pull request by martinfleis**
Closes #675

### CODE REVIEW

**Comment by ljwolf** [comment]
great implementation! two small thoughts
1. I think that it might be good to support applying `func` over the weights. So, something like `graph.apply('median')` gives you the median weight in each neighbor set. I don't mind if this looks like `graph.apply(None, 'median', **kwargs)`... 
2.  ...but this probably instead should look like `graph.apply('median', values=None, **kwargs)`, which matches the `func`-first way that `grouper.apply()` and `functools.reduce()` is written?

**Comment by martinfleis** [comment]
So apply `func` over weights if `values` are not set and otherwise ignore `weights` and apply `func` over `values`? I am on the verge whether it can be potentially confusing or not, meaning if it should not be two methods rather than one.

**Comment by jGaboardi** [comment]
> I am on the verge whether it can be potentially confusing or not, meaning if it should not be two methods rather than one.

I agree on the "potentially confusing" part and think 2 distinct methods might be a good idea.

**Comment by knaaptime** [comment]
nice. two quick reactions

1. i think the really nice thing about the graph, especially compared to the old implementation, is how easy it is to do these kind of manipulations manually because of the way the pandas structure works underneath. An apply func is nice, but i think it would actually be more useful to demo these kinds of things in a tutorial so folks know how to actually manipulate a graph at will. You couldnt do that kinda thing with a W

2. couldnt this just be `g._adjacency.groupby(level=0).transform(func)`? like [i initially sketched](https://github.com/pysal/libpysal/pull/513#issuecomment-1407586099) for the lags?

**Comment by martinfleis** [comment]
Actually not because `y` does not have the MultiIndex assigned.

**Comment by ljwolf** [comment]
Fine with that!

**Comment by martinfleis** [comment]
Added `aggregate` and allowed callable as transformation in `transform`.

**Comment by martinfleis** [comment]
It will need some examples but that applies to the rest of Graph as well :).

**Review by ljwolf — APPROVED** [review]
looks good to me!

**Review by knaaptime — APPROVED** [review]
sweet

**Review by jGaboardi — APPROVED** [review]

**Pull request merged**
